CREATE SEQUENCE cep_seq INCREMENT 1 START 1;
CREATE SEQUENCE idCliente_seq INCREMENT 1 START 1;
CREATE SEQUENCE cód_entrega_seq INCREMENT 1 START 1;
CREATE SEQUENCE idFornecedor_seq INCREMENT 1 START 1;
CREATE SEQUENCE idFuncionário_seq INCREMENT 1 START 1;
CREATE SEQUENCE cód_pagamento_seq INCREMENT 1 START 1;
CREATE SEQUENCE idProduto_seq INCREMENT 1 START 1;
CREATE SEQUENCE cód_trajeto_seq INCREMENT 1 START 1;